import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./theme-provider"; // テーマプロバイダー
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My Assistant App",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}>
      {/* ⭕ htmlタグのすぐ内側、bodyタグの「外側」をThemeProviderで完全に包みます */}
      <ThemeProvider>
        <body className="min-h-full flex flex-col">
          {children}
        </body>
      </ThemeProvider>
    </html>
  );
}