import type { Metadata, Viewport } from "next";
import { IBM_Plex_Sans_JP } from "next/font/google";
import "./globals.css";

const ibmPlexSansJP = IBM_Plex_Sans_JP({
  variable: "--font-sans",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "My Assistant App",
  description: "Generated by Next.js",
  manifest: "/manifest.json",
  appleWebApp: {
    capable: true,
    title: "AI秘書",
    statusBarStyle: "default",
  },
  icons: {
    apple: "/icon-512x512.png",
  },
};

export const viewport: Viewport = {
  themeColor: "#3b3a4e",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" className={ibmPlexSansJP.variable}>
      <body className="min-h-full flex flex-col">
        {children}
      </body>
    </html>
  );
}